name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-format:
    name: Lint Format (Clang-Format)
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/${{ github.repository }}/build-native:latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure CMake (Dry Run Format)
      run: cmake -B build -S . -DFORMAT_DRY_RUN=ON -DFETCHCONTENT_FULLY_DISCONNECTED=ON

    - name: Check Formatting
      run: cmake --build build --target caffeine-hal-format

  static-analysis:
    name: Static Analysis (Cppcheck & Clang-Tidy)
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/${{ github.repository }}/build-native:latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure CMake
      run: cmake -B build -S . -DFETCHCONTENT_FULLY_DISCONNECTED=ON

    - name: Run Analysis
      run: |
        cmake --build build --target caffeine-hal-analyze
        cmake --build build --target caffeine-hal-compliance

  build-and-test:
    name: Build & Unit Tests
    runs-on: ubuntu-24.04
    needs: [lint-format]
    container:
      image: ghcr.io/${{ github.repository }}/build-native:latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure CMake
      run: cmake -B build -S . -DFETCHCONTENT_FULLY_DISCONNECTED=ON

    - name: Build Tests
      run: cmake --build build --target caffeine-hal-test -j 4

    - name: Run Unit Tests
      run: ctest --test-dir build --output-on-failure

  docs-generation:
    name: Documentation Generation (Doxygen)
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/${{ github.repository }}/build-native:latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure CMake
      run: cmake -B build -S . -DFETCHCONTENT_FULLY_DISCONNECTED=ON

    - name: Build Doxygen Target
      run: cmake --build build --target caffeine-hal-docs
