name: Automatic SemVer Bump

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  bump-version:
    uses: while-one/caffeine-build/.github/workflows/version-bump.yml@main
    secrets: inherit
